services:
  - type: web
    name: ddr4d-adoption-dashboard
    runtime: static
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
